// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZ9629qZ38VZR4yPYz35bKdyCNr5NCzU',
    appId: '1:315489372903:web:bb10338a3f6c11c5947042',
    messagingSenderId: '315489372903',
    projectId: 'exercise2-5f0ea',
    authDomain: 'exercise2-5f0ea.firebaseapp.com',
    storageBucket: 'exercise2-5f0ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmuEd1MP5NpGDHeBHK5HEZZVIw1lw1sQA',
    appId: '1:315489372903:android:d379bb684fa94024947042',
    messagingSenderId: '315489372903',
    projectId: 'exercise2-5f0ea',
    storageBucket: 'exercise2-5f0ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMlvCit4uKgAbyaQ351AJ7adZjGNLVgKw',
    appId: '1:315489372903:ios:4ad586d4fd04e6e6947042',
    messagingSenderId: '315489372903',
    projectId: 'exercise2-5f0ea',
    storageBucket: 'exercise2-5f0ea.appspot.com',
    iosClientId: '315489372903-odb2ufvm8v7e2h9ibv0cuimoe1241ppn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase2',
  );
}
